### ISSUE TITLE
Red Icon when trying to upload ipa. Cannot upload.

### ISSUE THREAD

**Issue by whaleyHF** [nolanbrown/appsendr-mac#3]
It appears the HTTPS cert on your site expired yesterday.

I think this might be effecting app uploads.  Whenever I try to upload a file I just see the tray icon turn red and it seems to fail.

![screen shot 2015-02-03 at 3 29 18 pm](https://cloud.githubusercontent.com/assets/3028701/6029952/79f71e98-abb9-11e4-90d0-ad9f2af14af5.png)

**Comment by nolanbrown** [comment]
Updated certificate. Apologies for the delay in updating.
