### ISSUE TITLE
Certificate issue for appsendr.com

### ISSUE THREAD

**Issue by dannyl07** [nolanbrown/appsendr-mac#4]
Seems like appsendr.com's security certificate is invalid for https.

Edit:  Sorry, just saw somebody else has submitted the same issue.

**Comment by nolanbrown** [comment]
Updated certificate. Apologies for the delay in updating.

**Comment by oshevans** [comment]
Still having the same issue.. will it take some time to come through?

**Comment by oshevans** [comment]
Hah, just saw the date - this is a year old... looks we're having the same issue again this year.
