### ISSUE TITLE
Download link from www.appsendr.com doesn't work

### ISSUE THREAD

**Issue by DrMoriarty** [nolanbrown/appsendr-mac#5]
Sorry for making an issue, I can't find any other contacts.

You forget to set read permissions for everyone.
URL https://s3.amazonaws.com/assets.ota.io/mac/AppSendr_1.1.zip

    <Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>0FB5605E000E30A4</RequestId>
    <HostId>
    +V1CHQHoOjxlDxkyKZ1wbrj1ao13mPSGiXzjd0SqET9KhKOOLx75UfVCEbLThet58u+8NBGZQ3I=
    </HostId>
    </Error>

**Comment by nolanbrown** [comment]
Fixed.
