### ISSUE TITLE
SSL cert error again?

### ISSUE THREAD

**Issue by dannyl07** [nolanbrown/appsendr-mac#6]
upload url: https://api.appsendr.com/v1/app/new
            status code: None
            error: connection failed (SSLError(SSLError(CertificateError("hostname 'api.appsendr.com' doesn't match either of 'ota.io', 'www.ota.io'",),),))
            url: None
            response_json: None
            response_text: None

**Comment by dannyl07** [comment]
Got around the SSL error by telling uploader to not validate certificate, but now I'm getting a 413, request entity too large in the response.

**Comment by whaleyHF** [comment]
I'm seeing a similar issue uploading.  I'm using the Mac client.

The UI seems to indicate that the upload is going through, but then it dies at the very end (see image)

![appsendr](https://cloud.githubusercontent.com/assets/3028701/6531180/bd3f6d4e-c3fc-11e4-92fe-9fbf8672156e.gif)

**Comment by hansemannn** [comment]
Having the same problems here. Stopped working since about one week. No twitter responses and no alternatives. Mhhh!

**Comment by whaleyHF** [comment]
I transitioned to Test Flight in iTunes Connect.  It's pretty nice for sharing builds with iOS8 users.  It takes about 20 minutes for Apple to process the build, but aside from that it's pretty nice when you get used to it.

For iOS7 users I'm just emailing them adhoc builds and having them install manually in iTunes.  I'd prefer it if I could do OTA builds, but it works.

**Comment by hansemannn** [comment]
I'm no fan of TestFlight in iTC, yet. You must sign the application with a production certificate, upload it through XCode, select the beta in iTC, enter emails, submit it for beta review. OTA always seemed perfect.

**Comment by nolanbrown** [comment]
I'm trying to duplicate the error. We updated SSL certs is probably contributing to the issue. I've been able to successfully upload via CURL and the Status Bar app.

**Comment by nolanbrown** [comment]
FYI, there is a new Mac app version available (https://s3.amazonaws.com/assets.ota.io/mac/AppSendr_1.1.zip). Let me know where you're experience any issues at (CURL, Gem, App, etc).

**Comment by hansemannn** [comment]
@nolanbrown Still having problems with the 1.1 version (using Mac Status Bar app). The upload starts and fails after ~ 20 seconds with an red icon.

**Comment by nolanbrown** [comment]
What was the size of your app? I just increased the app upload size.

**Comment by dannyl07** [comment]
It was about 5MB.

**Comment by hansemannn** [comment]
My was about 5,5 MB. Earlier uploads from 2014 with large APK's (12MB+) also used to work. Will try again and edit asap!

**Comment by nolanbrown** [comment]
Great! Sorry for the hiccup.

**Comment by oshevans** [comment]
Hi, seems we have the same problem again this year.

**Comment by hansemannn** [comment]
Worked since last year, but having the same issue again since 2 days. @nolanbrown any ideas? App size is 5.3mb.

**Comment by nolanbrown** [comment]
I'm fixing it now. Sorry for the issue everyone. Same deal as last year, SSL expired and I got no notification.

**Comment by nolanbrown** [comment]
Took a little while to get the SSL certification but everything is back up. Sorry for the downtime.

**Comment by hansemannn** [comment]
Thank you @nolanbrown! I would like to give something back by paying the ssl costs this year. Can you provide an paypal address in private? Thank you!
