### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by alexmipego** [nolanbrown/appsendr-mac#9]
The ota.io site SSL certificate has expired.

I would also like to leave a suggestion, use https://letsencrypt.org/ to get free SSL certs, and their community also has scripts/tools to automatically renew certificates. The process can be automated to the point you never have to waste time with this issue ;)

**Comment by kidandcat** [comment]
The certificate has been updated by @nolanbrown , you can close this issue @alexmipego :)

**Comment by alexmipego** [comment]
Thanks!
